pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') { 
            agent {
                docker {
                    image 'maven:3.9.9-amazoncorretto-17'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'maven:3.9.9-amazoncorretto-17'
                }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            agent {
                docker {
                    image 'maven:3.9.9-amazoncorretto-17'
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}